language: java
jdk:
  - oraclejdk11

sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.m2/repository

script:
  - ./gradlew test 
  - ./gradlew build

before_deploy: ./before_deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    tags: true
